import 'package:flutter/material.dart';

import 'wgt_pag_item_finder_flexi.dart';

class WgtPagItemFinderFlexi2 extends WgtPagItemFinderFlexi {
  const WgtPagItemFinderFlexi2({
    super.key,
    required super.loggedInUser,
    required super.appConfig,
    required super.itemKind,
    required super.itemType,
    required super.listController,
    required super.listContextType,
    required super.onResult,
    required super.projectId,
    required super.aclResLabel,
    super.selectedItemInfoList,
    super.meterTypeList = const [],
    super.sectionName = '',
    super.panelName = '',
    super.panelTitle = '',
    super.width,
    super.onModified,
    super.onSearching,
    super.onClearSearch,
    super.identifySingleItem = false,
    super.getCountOnly = false,
    super.showTimeRangePicker = false,
    super.timeRangePickerWidget,
    super.initialType,
    super.initialNoR,
    super.iniShowPanel,
    super.onShowPanel,
    super.sidePadding = EdgeInsets.zero,
    super.onLabelSelected,
    super.onCustomizeSet,
    super.validator,
    super.isCompactMode = false,
    super.isSingleItemMode = false,
    super.initialFilterMap = const {},
    super.initialFilterGroupType,
    super.isInitialValueMutable = false,
    super.allowFlexiLabel = false,
    super.hint,
    super.widthOffset = 0.0,
    super.additionalQuery = const {},
    super.maxDurationDays,
    super.sortBy,
    super.sortOrder,
    super.isScopeProvider = false,
    super.onScopeChanged,
    super.prevailingScopeProfile,
    super.enableSearch = true,
    super.autoCascadeScopeFilter = true,
    super.loadOnInit = false,
  }) : super(useServerPinPreference: true);
}
